### ISSUE TITLE
wandb (Weights and Biases) logging included in the code

### ISSUE THREAD

**Issue by rmcdomaths** [marrlab/SHAPR_torch#4]
I have not used wandb before but it seems to be an alternative to traditional Python logging which saves logs to a website? I have not been able to run the code with the references to wandb included (it requires a login and then refuses access to this project). The code seems to work if I comment out any reference to wandb, but rather than submitting a pull request for this, I thought I would submit this Issue in case wandb has been intentionally left in? As far as I can see, there are only references to wandb in the main.py file.

**Comment by Pseudomanifold** [comment]
Yeah, the point of `wandb` would be to improve reproducibility. I think for using this in practice, it's indeed better to remove it or add a fail-safe handler. I think I'd go for removing—would you be okay with opening a PR for that?
