### ISSUE TITLE
Implementation Details: topo_feat_s

### ISSUE THREAD

**Issue by VincentYCYao** [marrlab/SHAPR_torch#6]
Hi,

In the `_settings.py` file, we have the default setting "topo_feat_s=False", which means "do no use superlevel features". But in the paper, the authors applied a superlevel set filtration, which means constructing cubical complexes by retaining vertices above a sequence of thresholds.

Could you answer the questions below?
1) which setting for "topo_feat_s" is used
2) from your experience, what is the effect of superlevel and sublevel set filtration? 

Best,
Vincent

**Comment by Pseudomanifold** [comment]
We typically ran sweeps in which we made the choice configurable (see `shapr/sweeps/topology-all-dims.yaml`). In practice, the choice does not make a substantial difference, given the [duality theorems](https://arxiv.org/abs/1107.5665). Hope that helps! Feel free to reopen.
